// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArvZG2yM48mc4mzr_OnsR6TFkm6AMgVqQ',
    appId: '1:20718115496:web:877bca31f28ed015d7809d',
    messagingSenderId: '20718115496',
    projectId: 'kharadi-assignmet',
    authDomain: 'kharadi-assignmet.firebaseapp.com',
    storageBucket: 'kharadi-assignmet.firebasestorage.app',
    measurementId: 'G-LW343YBB16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHXGYBv56oWQ5hb41aSwJSMcmUe94s8Jg',
    appId: '1:20718115496:android:dd45362abd2d03dad7809d',
    messagingSenderId: '20718115496',
    projectId: 'kharadi-assignmet',
    storageBucket: 'kharadi-assignmet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5qA8ZLtcO7DvF5VbwEGG8CXWk_EsIpEQ',
    appId: '1:20718115496:ios:f691cb8244f48e25d7809d',
    messagingSenderId: '20718115496',
    projectId: 'kharadi-assignmet',
    storageBucket: 'kharadi-assignmet.firebasestorage.app',
    iosBundleId: 'com.example.kharadiAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5qA8ZLtcO7DvF5VbwEGG8CXWk_EsIpEQ',
    appId: '1:20718115496:ios:f691cb8244f48e25d7809d',
    messagingSenderId: '20718115496',
    projectId: 'kharadi-assignmet',
    storageBucket: 'kharadi-assignmet.firebasestorage.app',
    iosBundleId: 'com.example.kharadiAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArvZG2yM48mc4mzr_OnsR6TFkm6AMgVqQ',
    appId: '1:20718115496:web:72099250abb42c04d7809d',
    messagingSenderId: '20718115496',
    projectId: 'kharadi-assignmet',
    authDomain: 'kharadi-assignmet.firebaseapp.com',
    storageBucket: 'kharadi-assignmet.firebasestorage.app',
    measurementId: 'G-2XHMPM20LH',
  );
}
